spring.application.name=api-gateway
server.port=8080

# JWT ? debe ser exactamente igual al de MS-Auth
jwt.secret=tienda-generica-secret-key-2024-muy-larga-para-seguridad
jwt.expiration=86400000

# URLs de microservicios
ms.auth.url=http://localhost:8081
ms.productos.url=http://localhost:8082
ms.usuarios.url=http://localhost:8083
ms.proveedores.url=http://localhost:8085
ms.clientes.url=http://localhost:8086
ms.ventas.url=http://localhost:8087
ms.reportes.url=http://localhost:8088

# Rutas Spring Cloud Gateway
spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=ms-productos
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/productos/**

spring.cloud.gateway.routes[2].id=ms-usuarios
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.routes[3].id=ms-proveedores
spring.cloud.gateway.routes[3].uri=http://localhost:8085
spring.cloud.gateway.routes[3].predicates[0]=Path=/proveedor/**

spring.cloud.gateway.routes[4].id=ms-clientes
spring.cloud.gateway.routes[4].uri=http://localhost:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/clientes/**

spring.cloud.gateway.routes[5].id=ms-ventas
spring.cloud.gateway.routes[5].uri=http://localhost:8087
spring.cloud.gateway.routes[5].predicates[0]=Path=/ventas/**

spring.cloud.gateway.routes[6].id=ms-reportes
spring.cloud.gateway.routes[6].uri=http://localhost:8088
spring.cloud.gateway.routes[6].predicates[0]=Path=/reportes/**