spring.application.name=api-gateway
server.port=8080

# JWT ? debe ser exactamente igual al de MS-Auth
jwt.secret=tienda-generica-secret-key-2024-muy-larga-para-seguridad
jwt.expiration=86400000

# URLs de microservicios (Usando nombres de servicio de Docker)
ms.auth.url=${MS_AUTH_URL:http://ms-auth:8081}
ms.productos.url=${MS_PRODUCTOS_URL:http://ms-productos:8082}
ms.usuarios.url=${MS_USUARIOS_URL:http://ms-usuarios:8083}
ms.proveedores.url=${MS_PROVEEDORES_URL:http://ms-proveedores:8085}
ms.clientes.url=${MS_CLIENTES_URL:http://ms-clientes:8086}
ms.ventas.url=${MS_VENTAS_URL:http://ms-ventas:8087}
ms.reportes.url=${MS_REPORTES_URL:http://ms-reportes:8088}

# Rutas Spring Cloud Gateway
spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=http://ms-auth:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=ms-productos
spring.cloud.gateway.routes[1].uri=http://ms-productos:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/productos/**

spring.cloud.gateway.routes[2].id=ms-usuarios
spring.cloud.gateway.routes[2].uri=http://ms-usuarios:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.routes[3].id=ms-proveedores
spring.cloud.gateway.routes[3].uri=http://ms-proveedores:8085
spring.cloud.gateway.routes[3].predicates[0]=Path=/proveedor/**

spring.cloud.gateway.routes[4].id=ms-clientes
spring.cloud.gateway.routes[4].uri=http://ms-clientes:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/clientes/**

spring.cloud.gateway.routes[5].id=ms-ventas
spring.cloud.gateway.routes[5].uri=http://ms-ventas:8087
spring.cloud.gateway.routes[5].predicates[0]=Path=/ventas/**
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[6].id=ms-reportes
spring.cloud.gateway.routes[6].uri=http://ms-reportes:8088
spring.cloud.gateway.routes[6].predicates[0]=Path=/reportes/**


# Ver el detalle de las rutas del Gateway
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.client=DEBUG